name: microfrontend-deployment

on:
    push:
        branches: [ main ]
        paths:
            - "web/**"

defaults:
    run:
        working-directory: .

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: checkout action
              uses: actions/checkout@v3

            - name: install node.JS
              uses: actions/setup-node@v2
              with:
                node-version: "16"

            - name: setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                version: 7
                run_install: false

            - name: add pnpm cache store directory
              run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - name: setup pnpm cache
              uses: actions/cache@v3
              with:
                path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: ${{ runner.os }}-pnpm-store-

            - name: install dependencies
              run: pnpm install

            - name: generate microfrontend builds
              run: pnpm nx build shared && pnpm nx build container

            - name: install and configure aws-cli
              uses: aws-actions/configure-aws-credentials@master
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: "us-west-1"

            - name: generate CloudFormation template
              run: pnpm cdk synth

            - name: bootstrap and deploy stack
              run: pnpm cdk bootstrap --all --require-approval never && pnpm cdk deploy --all --require-approval never